# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaltMinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124, verbose_name='Minion名称')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.SmallIntegerField(choices=[(1, '已经认证'), (2, '未认证')], verbose_name='认证状态')),
                ('Autherized_date', models.DateField(auto_now=True, verbose_name='认证时间')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': 'Salt认证',
                'verbose_name_plural': 'Salt认证',
            },
        ),
    ]
